from django.urls import path
from . import views

urlpatterns = [
    path('mine/',
          views.ManageInternshipListView.as_view(),
          name='manage_internship_list'),
    path('create/',
          views.InternshipCreateView.as_view(),
          name='internship_create'),
    path('<pk>/edit/',
          views.InternshipUpdateView.as_view(),
          name='internship_edit'),
    path('<pk>/delete/',
          views.InternshipDeleteView.as_view(),
          name='internship_delete'),
    path('<pk>/module/',
          views.InternshipModuleUpdateView.as_view(),
          name='internship_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/',
          views.ContentCreateUpdateView.as_view(),
          name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/',
          views.ContentCreateUpdateView.as_view(),
          name='module_content_update'),
    path('content/<int:id>/delete/',
         views.ContentDeleteView.as_view(),
         name='module_content_delete'),
    path('module/<int:module_id>/',
         views.ModuleContentListView.as_view(),
         name='module_content_list'),
    path('module/order/',
         views.ModuleOrderView.as_view(),
         name='module_order'),
    path('content/order/',
         views.ContentOrderView.as_view(),
         name='content_order'),
    path('area/<slug:area>/',
         views.InternshipListView.as_view(),
         name='internship_list_area'),
    path('<slug:slug>/',
         views.InternshipDetailView.as_view(),
         name='internship_detail'),
]
