# Generated by Django 3.2 on 2021-04-26 18:10

from django.db import migrations
import internship.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=internship.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=internship.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
