# Generated by Django 3.2 on 2021-06-02 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0003_auto_20210426_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='internship_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
